import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import AppHeader from "@/app/components/AppHeader/AppHeader";
import AppNavBar from "./components/AppNavBar/AppNavBar";
import UserProvider from "./components/Providers/UserProvider/UserProvider";
import SearchProvider from "./components/Providers/SearchProvider/SearchProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <SearchProvider>
            <AppHeader />
            <AppNavBar/>
            <main>{children}</main>
          </SearchProvider>
        </UserProvider>
      </body>
    </html>
  );
}
